const pokemonTypeColor = {
  normal: 'stone',
  fighting: 'rose',
  flying: 'sky',
  poison: 'violet',
  ground: 'neutral',
  rock: 'zinc',
  bug: 'lime',
  ghost: 'fuchsia',
  steel: 'gray',
  fire: 'red',
  water: 'blue',
  grass: 'green',
  electric: 'yellow',
  psychic: 'rose',
  ice: 'cyan',
  dragon: 'indigo',
  dark: 'stone',
  fairy: 'pink',
  unknown: 'stone',
  shadow: 'zinc',
};
export { pokemonTypeColor };
